baseURL = 'https://sanajitjana.github.io/'
# If this is a project site (not user/org site), change to:
# baseURL = 'https://sanajitjana.github.io/YOUR-REPO-NAME/'
languageCode = 'en-US'
title = 'Sanajit Jana'

theme = 'hugo-narrow'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
timeZone = 'UTC'

hasCJKLanguage = false
enableEmoji = true

[permalinks]
  posts = "/posts/:year/:month/:slug/"
  pages = "/:slug/"

[pagination]
  pagerSize = 6
  path = "page"

[taxonomies]
  category = "categories"
  tag = "tags"

# Header menu
[menus]
[[menus.main]]
  name = "Home"
  pageRef = "/"
  weight = 10
  [menus.main.params]
    icon = "home"
[[menus.main]]
  name = "Work"
  pageRef = "/work"
  weight = 20
  [menus.main.params]
    icon = "work"
[[menus.main]]
  name = "Projects"
  pageRef = "/projects"
  weight = 30
  [menus.main.params]
    icon = "folder"
[[menus.main]]
  name = "Posts"
  pageRef = "/posts"
  weight = 40
  [menus.main.params]
    icon = "posts"

[params]
  # Basic site info with SEO
  description = "I'm Sanajit Jana, a Full Stack Software Developer specializing in Java, Spring Boot, and Microservices. I build scalable and high-performance web applications using MySQL, PostgreSQL, Kafka, Docker, and AWS. Passionate about backend architecture, API development, cloud computing, and UI/UX design."
  keywords = ["Sanajit Jana", "Full Stack Developer", "Java Developer", "Spring Boot", "Microservices", "AWS", "Kafka", "Docker", "Kubernetes", "PostgreSQL", "MySQL", "REST API", "Backend Developer", "Frontend Developer", "Software Engineer", "CI/CD", "Redis", "Hibernate", "JPA", "JavaScript", "React", "HTML", "CSS", "UI/UX", "Web Development", "API Development", "Scalable Systems", "Cloud Computing", "DevOps", "Git", "GitHub", "Agile", "SDLC", "System Architecture", "Software Development"]
  defaultAuthor = "Sanajit Jana"
  language = "en-US"
  shortName = "Sanajit Jana"  # PWA
  images = ["/images/favicon.ico"]

  [params.logo]
    image = "/images/favicon.ico"  # Logo path rel to static folder, leave empty use site title and primary color
    link = "/"                  # click to home page
  [params.favicon]
    svg = "/images/favicon.ico"        # SVG format favicon (recommended)

  [params.author]
    name = "Sanajit Jana"
    title = "Software Engineer | Java, Spring Boot, Microservices, AWS"
    description = "Building scalable backends, cloud-native apps, and solving complex problems with clean code."
    avatar = "/images/sanajit-jana.webp"
    [[params.author.social]]
      name = "LinkedIn"
      url = "https://linkedin.com/in/sanajitjana01"
      icon = "linkedin"
    [[params.author.social]]
      name = "GitHub"
      url = "https://github.com/sanajitjana"
      icon = "github"
    [[params.author.social]]
      name = "Email"
      url = "mailto:sanajitjana01@gmail.com"
      icon = "email"

  # UI Components Control
  showThemeSwitch = true      # Set to false to hide theme style switcher (palette icon)
  showDarkModeSwitch = true   # Set to false to hide dark mode switcher (sun/moon icon)
  showLanguageSwitch = false
  languageSwitchMode = "dropdown"  # Language switch mode: "dropdown" (show panel) or "cycle" (direct cycle)

  # Header sticky effect
  stickyHeader = true  # Set to true to enable sticky navigation bar

  # Dock display mode
  # Options: "scroll" (show on scroll up), "always" (always visible), "float" (floating button)
  dock = "float"

  # Footer credits
  showPoweredBy = false  # Hide "Powered by Hugo & Narrow" from footer

  # default color scheme
  colorScheme = "default"

  [params.themes]
    [params.themes.default]
      name = "Default"
      order = 1
    [params.themes.claude]
      name = "Claude"
      order = 2
    [params.themes.bumblebee]
      name = "Bumblebee"
      order = 3
    [params.themes.emerald]
      name = "Emerald"
      order = 4
    [params.themes.nord]
      name = "Nord"
      order = 5
    [params.themes.sunset]
      name = "Sunset"
      order = 6
    [params.themes.abyss]
      name = "Abyss"
      order = 7
    [params.themes.dracula]
      name = "Dracula"
      order = 8
    [params.themes.amethyst]
      name = "Amethyst"
      order = 9
    [params.themes.slate]
      name = "Slate"
      order = 10
    [params.themes.twitter]
      name = "Twitter"
      order = 11

  [params.home]
    recentPostsCount = 5 # Number of recent posts to show on the home page

  [params.post]
    showRelated = true           # show related posts
    relatedPostsCount = 3        # posts number
    [params.post.license]
      show = true
      author = "Sanajit Jana"
      name = "CC BY-NC-SA 4.0"
      description = "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. Please attribute the source, use non-commercially, and maintain the same license."
      url = "https://creativecommons.org/licenses/by-nc-sa/4.0/"
      displayName = "CC BY-NC-SA 4.0"

# Footer menu
[[menus.footer]]
  name = "Home"
  pageRef = "/"
  weight = 10
  [menus.footer.params]
    icon = "home"
[[menus.footer]]
  name = "Posts"
  pageRef = "/posts"
  weight = 20
  [menus.footer.params]
    icon = "posts"
[[menus.footer]]
  name = "RSS Feed"
  url = "/index.xml"
  weight = 30
  [menus.footer.params]
    icon = "rss"

# Footer manu socials
[[menus.social]]
  name = "LinkedIn"
  url = "https://linkedin.com/in/sanajitjana01"
  weight = 10
  [menus.social.params]
    icon = "linkedin"
[[menus.social]]
  name = "GitHub"
  url = "https://github.com/sanajitjana"
  weight = 20
  [menus.social.params]
    icon = "github"
[[menus.social]]
  name = "Email"
  url = "mailto:sanajitjana01@gmail.com"
  weight = 30
  [menus.social.params]
    icon = "email"
  
  # comments
  [params.comments]
    enabled = false
    # giscus, disqus, utterances, waline, artalk, twikoo
    system = "giscus"
    [params.comments.giscus]
      repo = "tom2almighty/hugo-narrow-giscus"
      repoId = "R_kgDOO2gwLg"
      category = "General"
      categoryId = "DIC_kwDOO2gwLs4CrEaf"
      mapping = "pathname"
      strict = "0"
      reactionsEnabled = "1"
      emitMetadata = "0"
      inputPosition = "bottom"
      theme = "preferred_color_scheme"
      lang = "en"
    [params.comments.disqus]
      shortname = ""
    [params.comments.utterances]
      repo = "" 
      issueTerm = "pathname"
      label = "comment"
      theme = "preferred-color-scheme"
    [params.comments.waline]
      serverURL = ""
      lang = "zh-CN"
    [params.comments.artalk]
      server = ""
      site = ""
      locale = "zh-CN" # String|Object|"auto"
      darkMode = "auto"
      [params.comments.artalk.gravatar]
        mirror = "https://cravatar.cn/avatar/"
    [params.comments.twikoo]
      envId = ""
      region = "ap-shanghai"
      path = ""
      lang = "zh-CN"

  [params.analytics]
    enabled = false
    [params.analytics.baidu]
      enabled = false
      id = "your-baidu-analytics-id"
    [params.analytics.clarity]
      enabled = false
      analytics = "your-clarity-analytics-id"
    [params.analytics.google]
      enabled = false
      id = "your-google-analytics-id"
    [params.analytics.umami] 
      enabled = false
      id = "your-umami-website-id"
      src = "https://umami.com/myscript.js"
      domains = "example.domain.com"

  [params.katex]
    enabled = true
    [[params.katex.delimiters]]
      left = "$$"
      right = "$$"
      display = true
    [[params.katex.delimiters]]
      left = "$"
      right = "$"
      display = false
    [[params.katex.delimiters]]
      left = "\\("
      right = "\\)"
      display = false
    [[params.katex.delimiters]]
      left = "\\["
      right = "\\]"
      display = true

  [params.mermaid]
    enabled = true

  # GLightbox
  [params.lightbox]
    enabled = false
    loop = true
    width = "80vw"
    height = "80vh"
    touchNavigation = true
    draggable = true
    zoomable = true
    preload = true
    descPosition = "bottom"

  # Justified Gallery
  [params.justified_gallery]
    enabled = false
    rowHeight = 300
    gutter = 30
    lastRow = "center"
    transitionDuration = "0.3s"
    resizeDebounce = 100
    rowHeightTolerance = 0.25
    maxRowsCount = 999999
    calculateItemsHeight = false

  [params.codeblock]
    [params.codeblock.collapse]
      enabled = true
      defaultState = "expanded"  # expanded, collapsed
      autoCollapseLines = 30
      autoCollapseHeight = 400
      collapsedHeight = 120

  [params.readingProgress]
    enabled = true
    height = 3
    showOnHomepage = false
    smoothScroll = true
    hideOnComplete = false

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.delete]
          enable = true
        [markup.goldmark.extensions.extras.insert]
          enable = true
        [markup.goldmark.extensions.extras.mark]
          enable = true
        [markup.goldmark.extensions.extras.subscript]
          enable = false
        [markup.goldmark.extensions.extras.superscript]
          enable = false   
      strikethrough = false 
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = false
    lineNumbersInTable = false # Set to false
    noClasses = false
    style = "github" # No need to change
    tabWidth = 2

[outputs]
  home = ["HTML", "RSS", "JSON", "WebAppManifest"]
  section = ["HTML"]

# Custom output format
[outputFormats]
  [outputFormats.WebAppManifest]
    mediaType = "application/manifest+json"
    baseName = "site"
    isPlainText = true
